dist: focal

language: python

python:
  - 3.9

install:
  - pip install flake8
  - pip install isort
  - pip install black

script:
  - flake8 django_node_assets
  - isort django_node_assets --check
  - black django_node_assets --check
